services:
  nolongerevil:
    container_name: nolongerevil
    image: nolongerevil
    build: .
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8081:8081
    volumes:
      # Make sure to create your own env.local file. 
      # You can use the .env.example as a starting point.
      - ./env.local:/app/.env.local
      - nolongerevil-data:/app/data

volumes:
  nolongerevil-data: